"""
This type stub file was generated by pyright.
"""

class InvalidPaddingError(Exception):
    ...


class Padding:
    """Base class for padding and unpadding."""
    def __init__(self, block_size) -> None:
        ...
    
    def pad(self, value):
        ...
    
    def unpad(self, value):
        ...
    


class PKCS5Padding(Padding):
    """Provide PKCS5 padding and unpadding."""
    def pad(self, value):
        ...
    
    def unpad(self, value): # -> str | bytes:
        ...
    


class OneAndZeroesPadding(Padding):
    """Provide the one and zeroes padding and unpadding.

    This mechanism pads with 0x80 followed by zero bytes.
    For unpadding it strips off all trailing zero bytes and the 0x80 byte.
    """
    BYTE_80 = ...
    BYTE_00 = ...
    def pad(self, value):
        ...
    
    def unpad(self, value):
        ...
    


class ZeroesPadding(Padding):
    """Provide zeroes padding and unpadding.

    This mechanism pads with 0x00 except the last byte equals
    to the padding length. For unpadding it reads the last byte
    and strips off that many bytes.
    """
    BYTE_00 = ...
    def pad(self, value):
        ...
    
    def unpad(self, value): # -> str | bytes:
        ...
    


class NaivePadding(Padding):
    """Naive padding and unpadding using '*'.

    The class is provided only for backwards compatibility.
    """
    CHARACTER = ...
    def pad(self, value):
        ...
    
    def unpad(self, value):
        ...
    


PADDING_MECHANISM = ...
