"""
This type stub file was generated by pyright.
"""

import arrow

arrow = ...
class ArrowDateTime:
    def __init__(self) -> None:
        ...
    
    def process_bind_param(self, impl, value, dialect):
        ...
    
    def process_result_value(self, impl, value, dialect):
        ...
    


