"""
This type stub file was generated by pyright.
"""

from sqlalchemy import types
from ..scalar_coercible import ScalarCoercible

class EnrichedDateType(types.TypeDecorator, ScalarCoercible):
    """
    Supported for pendulum only.

    Example::


        from sqlalchemy_utils import EnrichedDateType
        import pendulum


        class User(Base):
            __tablename__ = 'user'
            id = sa.Column(sa.Integer, primary_key=True)
            birthday = sa.Column(EnrichedDateType(type="pendulum"))


        user = User()
        user.birthday = pendulum.datetime(year=1995, month=7, day=11)
        session.add(user)
        session.commit()
    """
    impl = types.Date
    cache_ok = ...
    def __init__(self, date_processor=..., *args, **kwargs) -> None:
        ...
    
    def process_bind_param(self, value, dialect): # -> None:
        ...
    
    def process_result_value(self, value, dialect): # -> Any | None:
        ...
    
    def process_literal_param(self, value, dialect): # -> str:
        ...
    
    @property
    def python_type(self):
        ...
    


