"""
This type stub file was generated by pyright.
"""

from sqlalchemy import types
from ..scalar_coercible import ScalarCoercible

class EnrichedDateTimeType(types.TypeDecorator, ScalarCoercible):
    """
    Supported for arrow and pendulum.

    Example::


        from sqlalchemy_utils import EnrichedDateTimeType
        import pendulum


        class User(Base):
            __tablename__ = 'user'
            id = sa.Column(sa.Integer, primary_key=True)
            created_at = sa.Column(EnrichedDateTimeType(type="pendulum"))
            # created_at = sa.Column(EnrichedDateTimeType(type="arrow"))


        user = User()
        user.created_at = pendulum.now()
        session.add(user)
        session.commit()
    """
    impl = types.DateTime
    cache_ok = ...
    def __init__(self, datetime_processor=..., *args, **kwargs) -> None:
        ...
    
    def process_bind_param(self, value, dialect): # -> None:
        ...
    
    def process_result_value(self, value, dialect): # -> Any | None:
        ...
    
    def process_literal_param(self, value, dialect): # -> str:
        ...
    
    @property
    def python_type(self):
        ...
    


