"""
This type stub file was generated by pyright.
"""

import pendulum

pendulum = ...
class PendulumDateTime:
    def __init__(self) -> None:
        ...
    
    def process_bind_param(self, impl, value, dialect):
        ...
    
    def process_result_value(self, impl, value, dialect):
        ...
    


