"""
This type stub file was generated by pyright.
"""

from functools import total_ordering
from ..utils import str_coercible

@str_coercible
@total_ordering
class WeekDay:
    NUM_WEEK_DAYS = ...
    def __init__(self, index) -> None:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __lt__(self, other) -> bool:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __unicode__(self):
        ...
    
    def get_name(self, width=..., context=...):
        ...
    
    @property
    def name(self):
        ...
    
    @property
    def position(self):
        ...
    


