"""
This type stub file was generated by pyright.
"""

from ..utils import str_coercible

@str_coercible
class WeekDays:
    def __init__(self, bit_string_or_week_days) -> None:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __iter__(self): # -> Generator[Any, Any, None]:
        ...
    
    def __contains__(self, value): # -> bool:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __unicode__(self): # -> str:
        ...
    
    def as_bit_string(self): # -> LiteralString:
        ...
    


