"""
This type stub file was generated by pyright.
"""

import contextlib

def create_mock_engine(bind, stream=...): # -> MockConnection | Engine:
    """Create a mock SQLAlchemy engine from the passed engine or bind URL.

    :param bind: A SQLAlchemy engine or bind URL to mock.
    :param stream: Render all DDL operations to the stream.
    """
    ...

@contextlib.contextmanager
def mock_engine(engine, stream=...): # -> Generator[StringIO | Any, Any, None]:
    """Mocks out the engine specified in the passed bind expression.

    Note this function is meant for convenience and protected usage. Do NOT
    blindly pass user input to this function as it uses exec.

    :param engine: A python expression that represents the engine to mock.
    :param stream: Render all DDL operations to the stream.
    """
    ...

