"""
This type stub file was generated by pyright.
"""

import sqlalchemy as sa
import sqlalchemy.orm
from sqlalchemy.sql.util import ClauseAdapter
from ..compat import _select_args
from .chained_join import chained_join

def path_to_relationships(path, cls): # -> list[Any]:
    ...

def adapt_expr(expr, *selectables): # -> None:
    ...

def inverse_join(selectable, left_alias, right_alias, relationship):
    ...

def relationship_to_correlation(relationship, alias): # -> None:
    ...

def chained_inverse_join(relationships, leaf_model): # -> tuple[Any, list[Any]]:
    ...

def select_correlated_expression(root_model, expr, path, leaf_model, from_obj=..., order_by=..., correlate=...):
    ...

