"""
This type stub file was generated by pyright.
"""

class PathException(Exception):
    ...


class DataException(Exception):
    ...


class with_backrefs:
    """
    Marks given attribute path so that whenever its fetched with batch_fetch
    the backref relations are force set too. Very useful when dealing with
    certain many-to-many relationship scenarios.
    """
    def __init__(self, path) -> None:
        ...
    


class Path:
    """
    A class that represents an attribute path.
    """
    def __init__(self, entities, prop, populate_backrefs=...) -> None:
        ...
    
    def validate_property(self, prop): # -> None:
        ...
    
    @property
    def session(self): # -> Session | None:
        ...
    
    @property
    def model(self):
        ...
    
    @classmethod
    def parse(cls, entities, path, populate_backrefs=...): # -> Path:
        ...
    
    @property
    def fetcher_class(self): # -> type[GenericRelationshipFetcher] | type[ManyToManyFetcher] | type[ManyToOneFetcher] | type[OneToManyFetcher]:
        ...
    


def batch_fetch(entities, *attr_paths): # -> None:
    """
    Batch fetch given relationship attribute for collection of entities.

    This function is in many cases a valid alternative for SQLAlchemy's
    subqueryload and performs lot better.

    :param entities: list of entities of the same type
    :param attr_paths:
        List of either InstrumentedAttribute objects or a strings representing
        the name of the instrumented attribute

    Example::


        from sqlalchemy_utils import batch_fetch


        users = session.query(User).limit(20).all()

        batch_fetch(users, User.phonenumbers)


    Function also accepts strings as attribute names: ::


        users = session.query(User).limit(20).all()

        batch_fetch(users, 'phonenumbers')


    Multiple attributes may be provided: ::


        clubs = session.query(Club).limit(20).all()

        batch_fetch(
            clubs,
            'teams',
            'teams.players',
            'teams.players.user_groups'
        )

    You can also force populate backrefs: ::


        from sqlalchemy_utils import with_backrefs


        clubs = session.query(Club).limit(20).all()

        batch_fetch(
            clubs,
            'teams',
            'teams.players',
            with_backrefs('teams.players.user_groups')
        )

    """
    ...

def get_fetcher(entities, path, populate_backrefs): # -> ManyToManyFetcher | ManyToOneFetcher | OneToManyFetcher | GenericRelationshipFetcher:
    ...

def fetcher_factory(entities, path): # -> CompositeFetcher | ManyToManyFetcher | ManyToOneFetcher | OneToManyFetcher | GenericRelationshipFetcher:
    ...

class CompositeFetcher:
    def __init__(self, *fetchers) -> None:
        ...
    
    @property
    def session(self):
        ...
    
    @property
    def model(self):
        ...
    
    @property
    def condition(self): # -> ColumnElement[bool]:
        ...
    
    @property
    def related_entities(self):
        ...
    
    def fetch(self): # -> None:
        ...
    
    def populate(self): # -> None:
        ...
    


class Fetcher:
    def __init__(self, path) -> None:
        ...
    
    @property
    def relation_query_base(self):
        ...
    
    @property
    def related_entities(self):
        ...
    
    def populate_backrefs(self, related_entities): # -> None:
        """
        Populates backrefs for given related entities.
        """
        ...
    
    def populate(self): # -> None:
        """
        Populate batch fetched entities to parent objects.
        """
        ...
    
    @property
    def condition(self): # -> Any | ColumnElement[bool]:
        ...
    
    def fetch(self): # -> None:
        ...
    


class GenericRelationshipFetcher:
    def __init__(self, path) -> None:
        ...
    
    def fetch(self): # -> None:
        ...
    
    def append_entity(self, entity): # -> None:
        ...
    
    def populate(self): # -> None:
        """
        Populate batch fetched entities to parent objects.
        """
        ...
    
    @property
    def related_entities(self): # -> chain[Any]:
        ...
    


class ManyToManyFetcher(Fetcher):
    @property
    def relation_query_base(self):
        ...
    
    def fetch(self): # -> None:
        ...
    


class ManyToOneFetcher(Fetcher):
    def append_entity(self, entity): # -> None:
        ...
    


class OneToManyFetcher(Fetcher):
    def append_entity(self, entity): # -> None:
        ...
    


