"""
This type stub file was generated by pyright.
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.sql.expression import ColumnElement, FunctionElement
from sqlalchemy.sql.functions import GenericFunction

class array_get(FunctionElement):
    name = ...


@compiles(array_get)
def compile_array_get(element, compiler, **kw): # -> str:
    ...

class row_to_json(GenericFunction):
    name = ...
    type = postgresql.JSON


@compiles(row_to_json, 'postgresql')
def compile_row_to_json(element, compiler, **kw): # -> LiteralString:
    ...

class json_array_length(GenericFunction):
    name = ...
    type = sa.Integer


@compiles(json_array_length, 'postgresql')
def compile_json_array_length(element, compiler, **kw): # -> LiteralString:
    ...

class Asterisk(ColumnElement):
    def __init__(self, selectable) -> None:
        ...
    


@compiles(Asterisk)
def compile_asterisk(element, compiler, **kw): # -> str:
    ...

