"""
This type stub file was generated by pyright.
"""

from sqlalchemy.orm import attributes
from sqlalchemy.orm.interfaces import MapperProperty, PropComparator

class GenericAttributeImpl(attributes.ScalarAttributeImpl):
    def get(self, state, dict_, passive=...): # -> Any | None:
        ...
    
    def get_state_discriminator(self, state): # -> Any:
        ...
    
    def get_state_id(self, state): # -> tuple[Any, ...]:
        ...
    
    def set(self, state, dict_, initiator, passive=..., check_old=..., pop=...): # -> None:
        ...
    


class GenericRelationshipProperty(MapperProperty):
    """A generic form of the relationship property.

    Creates a 1 to many relationship between the parent model
    and any other models using a descriminator (the table name).

    :param discriminator
        Field to discriminate which model we are referring to.
    :param id:
        Field to point to the model we are referring to.
    """
    def __init__(self, discriminator, id, doc=...) -> None:
        ...
    
    def init(self): # -> None:
        ...
    
    class Comparator(PropComparator):
        def __init__(self, prop, parentmapper) -> None:
            ...
        
        def __eq__(self, other) -> bool:
            ...
        
        def __ne__(self, other) -> bool:
            ...
        
        def is_type(self, other): # -> Any:
            ...
        
    
    
    def instrument_class(self, mapper): # -> None:
        ...
    


def generic_relationship(*args, **kwargs): # -> GenericRelationshipProperty:
    ...

