"""
This type stub file was generated by pyright.
"""

from sqlalchemy.ext.compiler import compiles
from sqlalchemy.sql.expression import ColumnElement

def get_locale():
    ...

def cast_locale(obj, locale, attr): # -> str | object:
    """
    Cast given locale to string. Supports also callbacks that return locales.

    :param obj:
        Object or class to use as a possible parameter to locale callable
    :param locale:
        Locale object or string or callable that returns a locale.
    """
    ...

class cast_locale_expr(ColumnElement):
    inherit_cache = ...
    def __init__(self, cls, locale, attr) -> None:
        ...
    


@compiles(cast_locale_expr)
def compile_cast_locale_expr(element, compiler, **kw): # -> str:
    ...

class TranslationHybrid:
    def __init__(self, current_locale, default_locale, default_value=...) -> None:
        ...
    
    def getter_factory(self, attr): # -> Callable[..., Any | None]:
        """
        Return a hybrid_property getter function for given attribute. The
        returned getter first checks if object has translation for current
        locale. If not it tries to get translation for default locale. If there
        is no translation found for default locale it returns None.
        """
        ...
    
    def setter_factory(self, attr): # -> Callable[..., None]:
        ...
    
    def expr_factory(self, attr): # -> Callable[..., coalesce[Any]]:
        ...
    
    def __call__(self, attr): # -> hybrid_property[Any]:
        ...
    


