"""
This type stub file was generated by pyright.
"""

import sqlalchemy as sa

def inspect_type(mixed): # -> TypeEngine[Any] | None:
    ...

def is_case_insensitive(mixed): # -> bool:
    ...

class CaseInsensitiveComparator(sa.Unicode.Comparator):
    @classmethod
    def lowercase_arg(cls, func): # -> Callable[..., Any]:
        ...
    
    def in_(self, other): # -> ColumnOperators:
        ...
    
    def notin_(self, other): # -> ColumnOperators:
        ...
    


string_operator_funcs = ...
