"""
This type stub file was generated by pyright.
"""

from .utils import str_coercible

@str_coercible
class Path:
    def __init__(self, path, separator=...) -> None:
        ...
    
    @property
    def parts(self):
        ...
    
    def __iter__(self): # -> Generator[Any, Any, None]:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def index(self, element):
        ...
    
    def __getitem__(self, slice): # -> Self:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __ne__(self, other) -> bool:
        ...
    
    def __unicode__(self): # -> Any:
        ...
    


def get_attr(mixed, attr): # -> Any:
    ...

@str_coercible
class AttrPath:
    def __init__(self, class_, path) -> None:
        ...
    
    def __iter__(self): # -> Generator[Any, Any, None]:
        ...
    
    def __invert__(self): # -> Self:
        ...
    
    def index(self, element): # -> int | None:
        ...
    
    @property
    def direction(self): # -> symbol:
        ...
    
    @property
    def uselist(self): # -> bool:
        ...
    
    def __getitem__(self, slice): # -> Self | list[Any]:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __ne__(self, other) -> bool:
        ...
    
    def __unicode__(self): # -> str:
        ...
    


