"""
This type stub file was generated by pyright.
"""

class ProxyDict:
    def __init__(self, parent, collection_name, mapping_attr) -> None:
        ...
    
    @property
    def collection(self): # -> Any:
        ...
    
    def keys(self): # -> list[Any]:
        ...
    
    def __contains__(self, key): # -> bool:
        ...
    
    def has_key(self, key): # -> bool:
        ...
    
    def fetch(self, key): # -> Any | None:
        ...
    
    def create_new_instance(self, key):
        ...
    
    def __getitem__(self, key): # -> Any:
        ...
    
    def __setitem__(self, key, value): # -> None:
        ...
    


def proxy_dict(parent, collection_name, mapping_attr):
    ...

def expire_proxy_dicts(target, context): # -> None:
    ...

