"""
This type stub file was generated by pyright.
"""

def str_coercible(cls):
    ...

def is_sequence(value): # -> bool:
    ...

def starts_with(iterable, prefix): # -> bool:
    """
    Returns whether or not given iterable starts with given prefix.
    """
    ...

