"""
This type stub file was generated by pyright.
"""

from sqlalchemy.ext import compiler
from sqlalchemy.schema import DDLElement

class CreateView(DDLElement):
    def __init__(self, name, selectable, materialized=...) -> None:
        ...
    


@compiler.compiles(CreateView)
def compile_create_materialized_view(element, compiler, **kw): # -> str:
    ...

class DropView(DDLElement):
    def __init__(self, name, materialized=..., cascade=...) -> None:
        ...
    


@compiler.compiles(DropView)
def compile_drop_materialized_view(element, compiler, **kw): # -> str:
    ...

def create_table_from_selectable(name, selectable, indexes=..., metadata=..., aliases=..., **kwargs): # -> Table:
    ...

def create_materialized_view(name, selectable, metadata, indexes=..., aliases=...): # -> Table:
    """ Create a view on a given metadata

    :param name: The name of the view to create.
    :param selectable: An SQLAlchemy selectable e.g. a select() statement.
    :param metadata:
        An SQLAlchemy Metadata instance that stores the features of the
        database being described.
    :param indexes: An optional list of SQLAlchemy Index instances.
    :param aliases:
        An optional dictionary containing with keys as column names and values
        as column aliases.

    Same as for ``create_view`` except that a ``CREATE MATERIALIZED VIEW``
    statement is emitted instead of a ``CREATE VIEW``.

    """
    ...

def create_view(name, selectable, metadata, cascade_on_drop=...): # -> Table:
    """ Create a view on a given metadata

    :param name: The name of the view to create.
    :param selectable: An SQLAlchemy selectable e.g. a select() statement.
    :param metadata:
        An SQLAlchemy Metadata instance that stores the features of the
        database being described.

    The process for creating a view is similar to the standard way that a
    table is constructed, except that a selectable is provided instead of
    a set of columns. The view is created once a ``CREATE`` statement is
    executed against the supplied metadata (e.g. ``metadata.create_all(..)``),
    and dropped when a ``DROP`` is executed against the metadata.

    To create a view that performs basic filtering on a table. ::

        metadata = MetaData()
        users = Table('users', metadata,
                Column('id', Integer, primary_key=True),
                Column('name', String),
                Column('fullname', String),
                Column('premium_user', Boolean, default=False),
            )

        premium_members = select(users).where(users.c.premium_user == True)
        # sqlalchemy 1.3:
        # premium_members = select([users]).where(users.c.premium_user == True)
        create_view('premium_users', premium_members, metadata)

        metadata.create_all(engine) # View is created at this point

    """
    ...

def refresh_materialized_view(session, name, concurrently=...): # -> None:
    """ Refreshes an already existing materialized view

    :param session: An SQLAlchemy Session instance.
    :param name: The name of the materialized view to refresh.
    :param concurrently:
        Optional flag that causes the ``CONCURRENTLY`` parameter
        to be specified when the materialized view is refreshed.
    """
    ...

