"""
This type stub file was generated by pyright.
"""

from functools import wraps
from sqlalchemy.orm.collections import InstrumentedList as _InstrumentedList
from .arrow import ArrowType
from .choice import Choice, ChoiceType
from .color import ColorType
from .country import CountryType
from .currency import CurrencyType
from .email import EmailType
from .encrypted.encrypted_type import EncryptedType, StringEncryptedType
from .enriched_datetime.enriched_date_type import EnrichedDateType
from .ip_address import IPAddressType
from .json import JSONType
from .locale import LocaleType
from .ltree import LtreeType
from .password import Password, PasswordType
from .pg_composite import CompositeType, register_composites, remove_composite_listeners
from .phone_number import PhoneNumber, PhoneNumberParseException, PhoneNumberType
from .range import DateRangeType, DateTimeRangeType, Int8RangeType, IntRangeType, NumericRangeType
from .scalar_list import ScalarListException, ScalarListType
from .timezone import TimezoneType
from .ts_vector import TSVectorType
from .url import URLType
from .uuid import UUIDType
from .weekdays import WeekDaysType
from .enriched_datetime.enriched_datetime_type import EnrichedDateTimeType

class InstrumentedList(_InstrumentedList):
    """Enhanced version of SQLAlchemy InstrumentedList. Provides some
    additional functionality."""
    def any(self, attr): # -> bool:
        ...
    
    def all(self, attr): # -> bool:
        ...
    


def instrumented_list(f): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], InstrumentedList]:
    ...

