"""
This type stub file was generated by pyright.
"""

import sqlalchemy as sa

class BitType(sa.types.TypeDecorator):
    """
    BitType offers way of saving BITs into database.
    """
    impl = sa.types.BINARY
    cache_ok = ...
    def __init__(self, length=..., **kwargs) -> None:
        ...
    
    def load_dialect_impl(self, dialect): # -> TypeEngine[int] | TypeEngine[str] | TypeEngine[Any]:
        ...
    


