"""
This type stub file was generated by pyright.
"""

from sqlalchemy import types
from .scalar_coercible import ScalarCoercible

class IPAddressType(ScalarCoercible, types.TypeDecorator):
    """
    Changes IPAddress objects to a string representation on the way in and
    changes them back to IPAddress objects on the way out.

    ::


        from sqlalchemy_utils import IPAddressType


        class User(Base):
            __tablename__ = 'user'
            id = sa.Column(sa.Integer, autoincrement=True)
            name = sa.Column(sa.Unicode(255))
            ip_address = sa.Column(IPAddressType)


        user = User()
        user.ip_address = '123.123.123.123'
        session.add(user)
        session.commit()

        user.ip_address  # IPAddress object
    """
    impl = ...
    cache_ok = ...
    def __init__(self, max_length=..., *args, **kwargs) -> None:
        ...
    
    def process_bind_param(self, value, dialect): # -> str | None:
        ...
    
    def process_result_value(self, value, dialect): # -> IPv4Address | IPv6Address | None:
        ...
    
    @property
    def python_type(self):
        ...
    


