"""
This type stub file was generated by pyright.
"""

import sqlalchemy as sa

has_postgres_json = ...
class JSONType(sa.types.TypeDecorator):
    """
    JSONType offers way of saving JSON data structures to database. On
    PostgreSQL the underlying implementation of this data type is 'json' while
    on other databases its simply 'text'.

    ::


        from sqlalchemy_utils import JSONType


        class Product(Base):
            __tablename__ = 'product'
            id = sa.Column(sa.Integer, autoincrement=True)
            name = sa.Column(sa.Unicode(50))
            details = sa.Column(JSONType)


        product = Product()
        product.details = {
            'color': 'red',
            'type': 'car',
            'max-speed': '400 mph'
        }
        session.commit()
    """
    impl = sa.UnicodeText
    hashable = ...
    cache_ok = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def load_dialect_impl(self, dialect): # -> TypeEngine[Any]:
        ...
    
    def process_bind_param(self, value, dialect): # -> str | None:
        ...
    
    def process_result_value(self, value, dialect): # -> Any | None:
        ...
    


