"""
This type stub file was generated by pyright.
"""

from sqlalchemy import types
from .scalar_coercible import ScalarCoercible

class LtreeType(types.Concatenable, types.UserDefinedType, ScalarCoercible):
    """Postgresql LtreeType type.

    The LtreeType datatype can be used for representing labels of data stored
    in hierarchical tree-like structure. For more detailed information please
    refer to https://www.postgresql.org/docs/current/ltree.html

    ::

        from sqlalchemy_utils import LtreeType, Ltree


        class DocumentSection(Base):
            __tablename__ = 'document_section'
            id = sa.Column(sa.Integer, autoincrement=True, primary_key=True)
            path = sa.Column(LtreeType)


        section = DocumentSection(path=Ltree('Countries.Finland'))
        session.add(section)
        session.commit()

        section.path  # Ltree('Countries.Finland')


    .. note::
        Using :class:`LtreeType`, :class:`LQUERY` and :class:`LTXTQUERY` types
        may require installation of Postgresql ltree extension on the server
        side. Please visit https://www.postgresql.org/ for details.
    """
    cache_ok = ...
    class comparator_factory(types.Concatenable.Comparator):
        def ancestor_of(self, other): # -> Operators:
            ...
        
        def descendant_of(self, other): # -> Operators:
            ...
        
        def lquery(self, other): # -> Operators:
            ...
        
        def ltxtquery(self, other): # -> Operators:
            ...
        
    
    
    def bind_processor(self, dialect): # -> Callable[..., Any | None]:
        ...
    
    def result_processor(self, dialect, coltype): # -> Callable[..., Ltree | None]:
        ...
    
    def literal_processor(self, dialect): # -> Callable[..., Any]:
        ...
    
    __visit_name__ = ...


class LQUERY(types.TypeEngine):
    """Postresql LQUERY type.
    See :class:`LTREE` for details.
    """
    __visit_name__ = ...


class LTXTQUERY(types.TypeEngine):
    """Postresql LTXTQUERY type.
    See :class:`LTREE` for details.
    """
    __visit_name__ = ...


def visit_LTREE(self, type_, **kw): # -> Literal['LTREE']:
    ...

def visit_LQUERY(self, type_, **kw): # -> Literal['LQUERY']:
    ...

def visit_LTXTQUERY(self, type_, **kw): # -> Literal['LTXTQUERY']:
    ...

