"""
This type stub file was generated by pyright.
"""

import passlib
from sqlalchemy import types
from sqlalchemy.ext.mutable import Mutable
from .scalar_coercible import ScalarCoercible

passlib = ...
class Password(Mutable):
    @classmethod
    def coerce(cls, key, value): # -> Password | Self | None:
        ...
    
    def __init__(self, value, context=..., secret=...) -> None:
        ...
    
    def __eq__(self, value) -> bool:
        ...
    
    def __ne__(self, value) -> bool:
        ...
    


class PasswordType(ScalarCoercible, types.TypeDecorator):
    """
    PasswordType hashes passwords as they come into the database and allows
    verifying them using a Pythonic interface. This Pythonic interface
    relies on setting up automatic data type coercion using the
    :func:`~sqlalchemy_utils.listeners.force_auto_coercion` function.

    All keyword arguments (aside from max_length) are forwarded to the
    construction of a `passlib.context.LazyCryptContext` object, which
    also supports deferred configuration via the `onload` callback.

    The following usage will create a password column that will
    automatically hash new passwords as `pbkdf2_sha512` but still compare
    passwords against pre-existing `md5_crypt` hashes. As passwords are
    compared; the password hash in the database will be updated to
    be `pbkdf2_sha512`.

    ::


        class Model(Base):
            password = sa.Column(PasswordType(
                schemes=[
                    'pbkdf2_sha512',
                    'md5_crypt'
                ],

                deprecated=['md5_crypt']
            ))


    Verifying password is as easy as:

    ::

        target = Model()
        target.password = 'b'
        # '$5$rounds=80000$H.............'

        target.password == 'b'
        # True


    Lazy configuration of the type with Flask config:

    ::


        import flask
        from sqlalchemy_utils import PasswordType, force_auto_coercion

        force_auto_coercion()

        class User(db.Model):
            __tablename__ = 'user'

            password = db.Column(
                PasswordType(
                    # The returned dictionary is forwarded to the CryptContext
                    onload=lambda **kwargs: dict(
                        schemes=flask.current_app.config['PASSWORD_SCHEMES'],
                        **kwargs
                    ),
                ),
                unique=False,
                nullable=False,
            )

    """
    impl = ...
    python_type = ...
    cache_ok = ...
    def __init__(self, max_length=..., **kwargs) -> None:
        ...
    
    @property
    def hashing_method(self): # -> Literal['hash', 'encrypt']:
        ...
    
    @property
    def length(self): # -> int:
        """Get column length."""
        ...
    
    def calculate_max_length(self): # -> int:
        ...
    
    def load_dialect_impl(self, dialect): # -> TypeEngine[bytes]:
        ...
    
    def process_bind_param(self, value, dialect): # -> Any | bytes | None:
        ...
    
    def process_result_value(self, value, dialect): # -> Password | None:
        ...
    
    @property
    def python_type(self):
        ...
    


