"""
This type stub file was generated by pyright.
"""

import psycopg2
from sqlalchemy.schema import _CreateDropBase
from sqlalchemy.sql.expression import FunctionElement
from sqlalchemy.types import SchemaType, UserDefinedType
from psycopg2.extensions import AsIs, adapt, register_adapter
from psycopg2.extras import CompositeCaster

"""
CompositeType provides means to interact with
`PostgreSQL composite types`_. Currently this type features:

* Easy attribute access to composite type fields
* Supports SQLAlchemy TypeDecorator types
* Ability to include composite types as part of PostgreSQL arrays
* Type creation and dropping

Installation
^^^^^^^^^^^^

CompositeType automatically attaches `before_create` and `after_drop` DDL
listeners. These listeners create and drop the composite type in the
database. This means it works out of the box in your test environment where
you create the tables on each test run.

When you already have your database set up you should call
:func:`register_composites` after you've set up all models.

::

    register_composites(conn)



Usage
^^^^^

::

    from collections import OrderedDict

    import sqlalchemy as sa
    from sqlalchemy_utils import CompositeType, CurrencyType


    class Account(Base):
        __tablename__ = 'account'
        id = sa.Column(sa.Integer, primary_key=True)
        balance = sa.Column(
            CompositeType(
                'money_type',
                [
                    sa.Column('currency', CurrencyType),
                    sa.Column('amount', sa.Integer)
                ]
            )
        )


Creation
~~~~~~~~
When creating CompositeType, you can either pass in a tuple or a dictionary.

::
    account1 = Account()
    account1.balance = ('USD', 15)

    account2 = Account()
    account2.balance = {'currency': 'USD', 'amount': 15}

    session.add(account1)
    session.add(account2)
    session.commit()


Accessing fields
^^^^^^^^^^^^^^^^

CompositeType provides attribute access to underlying fields. In the following
example we find all accounts with balance amount more than 5000.


::

    session.query(Account).filter(Account.balance.amount > 5000)


Arrays of composites
^^^^^^^^^^^^^^^^^^^^

::

    from sqlalchemy.dialects.postgresql import ARRAY


    class Account(Base):
        __tablename__ = 'account'
        id = sa.Column(sa.Integer, primary_key=True)
        balances = sa.Column(
            ARRAY(
                CompositeType(
                    'money_type',
                    [
                        sa.Column('currency', CurrencyType),
                        sa.Column('amount', sa.Integer)
                    ]
                ),
                dimensions=1
            )
        )


.. _PostgreSQL composite types:
    https://www.postgresql.org/docs/current/rowtypes.html


Related links:

https://schinckel.net/2014/09/24/using-postgres-composite-types-in-django/
"""
psycopg2 = ...
CompositeCaster = ...
adapt = ...
AsIs = ...
register_adapter = ...
class CompositeElement(FunctionElement):
    """
    Instances of this class wrap a Postgres composite type.
    """
    def __init__(self, base, field, type_) -> None:
        ...
    


registered_composites = ...
class CompositeType(UserDefinedType, SchemaType):
    """
    Represents a PostgreSQL composite type.

    :param name:
        Name of the composite type.
    :param columns:
        List of columns that this composite type consists of
    """
    python_type = ...
    class comparator_factory(UserDefinedType.Comparator):
        def __getattr__(self, key): # -> CompositeElement:
            ...
        
    
    
    def __init__(self, name, columns, quote=...) -> None:
        class Caster(CompositeCaster):
            ...
        
        
    
    def get_col_spec(self): # -> str | None:
        ...
    
    def bind_processor(self, dialect): # -> Callable[..., namedtuple | Any | None]:
        ...
    
    def result_processor(self, dialect, coltype): # -> Callable[..., Any | None]:
        ...
    
    def create(self, bind=..., checkfirst=...): # -> None:
        ...
    
    def drop(self, bind=..., checkfirst=...): # -> None:
        ...
    


def register_psycopg2_composite(dbapi_connection, composite): # -> None:
    ...

def before_create(target, connection, **kw): # -> None:
    ...

def after_drop(target, connection, **kw): # -> None:
    ...

def register_composites(connection): # -> None:
    ...

def attach_composite_listeners(): # -> None:
    ...

def remove_composite_listeners(): # -> None:
    ...

class CreateCompositeType(_CreateDropBase):
    ...


class DropCompositeType(_CreateDropBase):
    ...


