"""
This type stub file was generated by pyright.
"""

from sqlalchemy import exc, types
from ..utils import str_coercible
from .scalar_coercible import ScalarCoercible
from phonenumbers.phonenumber import PhoneNumber as BasePhoneNumber
from phonenumbers.phonenumberutil import NumberParseException

"""
..  note::

    The `phonenumbers`_ package must be installed to use PhoneNumber types.

..  _phonenumbers: https://github.com/daviddrysdale/python-phonenumbers
"""
class PhoneNumberParseException(NumberParseException, exc.DontWrapMixin):
    """
    Wraps exceptions from phonenumbers with SQLAlchemy's DontWrapMixin
    so we get more meaningful exceptions on validation failure instead of the
    StatementException

    Clients can catch this as either a PhoneNumberParseException or
    NumberParseException from the phonenumbers library.
    """
    ...


@str_coercible
class PhoneNumber(BasePhoneNumber):
    """
    Extends a PhoneNumber class from `Python phonenumbers library`_. Adds
    different phone number formats to attributes, so they can be easily used
    in templates. Phone number validation method is also implemented.

    Takes the raw phone number and country code as params and parses them
    into a PhoneNumber object.

    .. _Python phonenumbers library:
       https://github.com/daviddrysdale/python-phonenumbers


    ::

        from sqlalchemy_utils import PhoneNumber


        class User(self.Base):
            __tablename__ = 'user'
            id = sa.Column(sa.Integer, autoincrement=True, primary_key=True)
            name = sa.Column(sa.Unicode(255))
            _phone_number = sa.Column(sa.Unicode(20))
            country_code = sa.Column(sa.Unicode(8))

            phone_number = sa.orm.composite(
                PhoneNumber,
                _phone_number,
                country_code
            )


        user = User(phone_number=PhoneNumber('0401234567', 'FI'))

        user.phone_number.e164  # '+358401234567'
        user.phone_number.international  # '+358 40 1234567'
        user.phone_number.national  # '040 1234567'
        user.country_code  # 'FI'


    :param raw_number:
        String representation of the phone number.
    :param region:
        Region of the phone number.
    :param check_region:
        Whether to check the supplied region parameter;
        should always be True for external callers.
        Can be useful for short codes or toll free
    """
    def __init__(self, raw_number, region=..., check_region=...) -> None:
        ...
    
    def __composite_values__(self): # -> tuple[Any, Any | None]:
        ...
    
    def is_valid_number(self):
        ...
    
    def __unicode__(self):
        ...
    
    def __hash__(self) -> int:
        ...
    


class PhoneNumberType(ScalarCoercible, types.TypeDecorator):
    """
    Changes PhoneNumber objects to a string representation on the way in and
    changes them back to PhoneNumber objects on the way out. If E164 is used
    as storing format, no country code is needed for parsing the database
    value to PhoneNumber object.

    ::

        class User(self.Base):
            __tablename__ = 'user'
            id = sa.Column(sa.Integer, autoincrement=True, primary_key=True)
            name = sa.Column(sa.Unicode(255))
            phone_number = sa.Column(PhoneNumberType())


        user = User(phone_number='+358401234567')

        user.phone_number.e164  # '+358401234567'
        user.phone_number.international  # '+358 40 1234567'
        user.phone_number.national  # '040 1234567'
    """
    STORE_FORMAT = ...
    impl = ...
    python_type = ...
    cache_ok = ...
    def __init__(self, region=..., max_length=..., *args, **kwargs) -> None:
        ...
    
    def process_bind_param(self, value, dialect): # -> LiteralString | Any | None:
        ...
    
    def process_result_value(self, value, dialect): # -> PhoneNumber | Any | None:
        ...
    


