"""
This type stub file was generated by pyright.
"""

from sqlalchemy import types
from .scalar_coercible import ScalarCoercible

class TimezoneType(ScalarCoercible, types.TypeDecorator):
    """
    TimezoneType provides a way for saving timezones objects into database.
    TimezoneType saves timezone objects as strings on the way in and converts
    them back to objects when querying the database.

    ::

        from sqlalchemy_utils import TimezoneType

        class User(Base):
            __tablename__ = 'user'

            # Pass backend='pytz' to change it to use pytz. Other values:
            # 'dateutil' (default), and 'zoneinfo'.
            timezone = sa.Column(TimezoneType(backend='pytz'))

    :param backend: Whether to use 'dateutil', 'pytz' or 'zoneinfo' for
        timezones. 'zoneinfo' uses the standard library module in Python 3.9+,
        but requires the external 'backports.zoneinfo' package for older
        Python versions.

    """
    impl = ...
    python_type = ...
    cache_ok = ...
    def __init__(self, backend=...) -> None:
        ...
    
    def process_bind_param(self, value, dialect): # -> str | None:
        ...
    
    def process_result_value(self, value, dialect): # -> ZoneInfo | tzfile | _UTCclass | StaticTzInfo | DstTzInfo | None:
        ...
    


