"""
This type stub file was generated by pyright.
"""

from sqlalchemy import types
from .scalar_coercible import ScalarCoercible

sqlalchemy_version = ...
class UUIDType(ScalarCoercible, types.TypeDecorator):
    """
    Stores a UUID in the database natively when it can and falls back to
    a BINARY(16) or a CHAR(32) when it can't.

    ::

        from sqlalchemy_utils import UUIDType
        import uuid

        class User(Base):
            __tablename__ = 'user'

            # Pass `binary=False` to fallback to CHAR instead of BINARY
            id = sa.Column(
                UUIDType(binary=False),
                primary_key=True,
                default=uuid.uuid4
            )
    """
    impl = ...
    python_type = ...
    cache_ok = ...
    def __init__(self, binary=..., native=...) -> None:
        """
        :param binary: Whether to use a BINARY(16) or CHAR(32) fallback.
        """
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def load_dialect_impl(self, dialect): # -> TypeEngine[UUID] | TypeEngine[str]:
        ...
    
    if sqlalchemy_version < (1, 4, 30):
        def process_literal_param(self, value, dialect): # -> str | None:
            ...
        
    else:
        def process_literal_param(self, value, dialect): # -> None:
            ...
        
    def process_bind_param(self, value, dialect): # -> str | bytes | None:
        ...
    
    def process_result_value(self, value, dialect): # -> UUID | None:
        ...
    


