from datetime import datetime
from typing import List

from pydantic import BaseModel


# Defines shared base fields for the customer-generator join entity.
# Represents the many-to-many relationship between a customer and a
# hydrogen generator, including quantity and installation date.
class CustomerGeneratorAssetBaseSchema(BaseModel):

    customer_id: int        # FK to the Customer who owns the asset
    generator_id: int       # FK to the HydrogenGenerator model assigned
    generator_qtd: int      # number of generator units installed
    installation_date: datetime  # date the generator(s) were installed


# Defines the input payload used to create or update a customer-generator link.
# installation_date is optional; if omitted, the application can default it.
class CustomerGeneratorAssetSchema(BaseModel):

    customer_id: int
    generator_id: int
    generator_qtd: int
    installation_date: datetime | None = None  # defaults to None if not provided


# Defines the response schema for reading a single customer-generator link.
# Extends the base schema with the surrogate primary key (asset_id).
class CustomerGeneratorAssetViewSchema(CustomerGeneratorAssetBaseSchema):

    asset_id: int  # surrogate PK generated by the database


# Defines query parameters used to look up a specific asset link by ID.
class CustomerGeneratorAssetSearchSchema(BaseModel):

    asset_id: int = 1  # ID of the asset link to retrieve (defaults to 1)


# Defines the response schema for listing all customer-generator links.
class CustomerGeneratorAssetListSchema(BaseModel):

    assets: List[CustomerGeneratorAssetViewSchema]  # list of all asset links


# Defines the response schema returned after deleting a customer-generator link.
class CustomerGeneratorAssetDeleteSchema(BaseModel):

    message: str    # human-readable confirmation message
    asset_id: int   # ID of the asset link that was removed